services:
  scheduler:
    image: scheduler
    container_name: void-scheduler
    environment:
      - CONFIG_PATH=/app/config/dev.yaml
    volumes:
      - ./config:/app/config
      - ./sandbox:/app/sandbox
      - ~/.orbstack/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - void-network

networks:
  void-network:
    name: void-network
    external: true
